{% set name = "enlighten" %}
{% set version = "1.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7a5b83cd0f4d095e59d80c648ebb5f7ffca0cd8bcf7ae6639828ee1ad000632a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=2.7,!=3.0,!=3.1,!=3.2,!=3.3,<4
  run:
    - python >=2.7,!=3.0,!=3.1,!=3.2,!=3.3,<4
    - blessed >=1.17.7
    - prefixed >=0.3.2

test:
  imports:
    - enlighten
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://python-enlighten.readthedocs.io/en/stable/
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Enlighten Progress Bar
  doc_url: https://python-enlighten.readthedocs.io/en/stable/
  dev_url: https://github.com/Rockhopper-Technologies/enlighten

extra:
  recipe-maintainers:
    - fcollonval
